version: '3.4'

services:
  stubhub-api:
    image: stubhub-api
    container_name: stubhub-api
    ports:
      - '3004:3004'
    networks:
      default:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - '8000:8000'
    networks:
      default:
  backend:
    image: backend
    container_name: backend
    environment:
      STUBHUB_TOKEN: ${STUBHUB_TOKEN}
    env_file:
      - local.env
    ports:
      - '9000:9000'
    depends_on:
      - dynamodb-init
      - stubhub-api
    networks:
      default:
networks:
  default:
    name: stubhub
